# Generated by Django 5.0.6 on 2025-01-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0002_useraccount_email_useraccount_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='Administrateur.person'),
        ),
    ]
