# Generated by Django 5.0.6 on 2025-01-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du Shift')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('break_duration', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Durée de pause (en heures)')),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pointage', models.DateField(verbose_name='Date du pointage')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name="Heure d'entrée")),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Heure de sortie')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Heures travaillées')),
                ('status', models.CharField(choices=[('Present', 'Présent'), ('Absent', 'Absent'), ('Late', 'En retard'), ('Excused', 'Excusé')], default='Present', max_length=10, verbose_name='Statut')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pointage', to='Administrateur.person')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.shift')),
            ],
        ),
    ]
