# Generated by Django 5.0.6 on 2025-01-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='status',
            field=models.CharField(choices=[('Present', 'Présent'), ('Absent', 'Absent'), ('Late', 'En retard'), ('Excused', 'Excusé'), ('Cong', 'Congé')], default='Present', max_length=10, verbose_name='Statut'),
        ),
    ]
