# Generated by Django 5.0.6 on 2025-01-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0003_alter_useraccount_employee'),
        ('Manager', '0002_alter_pointage_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pointage',
            constraint=models.UniqueConstraint(fields=('person', 'date_pointage'), name='unique_pointage_per_employee'),
        ),
    ]
