# Generated by Django 5.0.6 on 2025-01-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_pointage_unique_pointage_per_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='date_pointage',
            field=models.DateField(auto_now_add=True, verbose_name='Date du pointage'),
        ),
    ]
